AutoZdam/AutoZdam/urls.py
from django.contrib import admin
from django.urls import path
from Auto_Zdam import views as az_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from Auto_Zdam.tokens import user_tokenizer

urlpatterns = [
    path('', az_views.MainView.as_view(), name="main"),
    path('offer_list', az_views.OfferListView.as_view(), name="offer_list"),
    path('admin/', admin.site.urls),
    path('offer/', az_views.AddOffer.as_view(), name="add_offer"),
    path('user_create/', az_views.UserCreate.as_view(), name='user_create'),
    path('equip/', az_views.EquipCreate.as_view(), name="add_equip"),
    path('user_login/', az_views.UserLoginView.as_view(), name='user-login'),
    path('user_logout/', az_views.UserLogoutView.as_view(), name='user-logout'),
    path('offer_details/<int:id>', az_views.OfferDetails.as_view(), name='offer-details'),
    path('offer_update/<int:pk>', az_views.OfferUpdate.as_view(), name="offer-update"),
    path('offer_delete/<int:pk>', az_views.OfferDelete.as_view(), name="offer-delete"),
    path('offer_msg/<int:id>', az_views.ContactFormView.as_view(), name="offer-msg"),
    path('myview', az_views.MyView.as_view(), name="my-view"),
    path('confirm-email/<str:user_id>/<str:token>/', az_views.ConfirmRegistrationView.as_view(), name='confirm_email'),
    path('reset-password/', auth_views.PasswordResetView.as_view(
      template_name='Auto_Zdam/reset_password.html',
      html_email_template_name='Auto_Zdam/reset_password_email.html',
      success_url="/",
      token_generator=user_tokenizer),
    name='reset_password'
  ),
path(
    'reset-password-confirmation/<str:uidb64>/<str:token>/',
    auth_views.PasswordResetConfirmView.as_view(
      template_name='Auto_Zdam/reset_password_update.html',
      post_reset_login=True,
      post_reset_login_backend='django.contrib.auth.backends.ModelBackend',
      token_generator=user_tokenizer,
      success_url="/"),
    name='password_reset_confirm'
  ),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AutoZdam/Auto_Zdam/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _



DOORS_NUMBER = (
    (1, "3"),
    (2, "5"),
)

SEATS_NUMBER = (
    (1, "2"),
    (2, "4"),
    (3, "5"),
    (4, "6")
)

FUEL_TYPE = (
    (1, "benzyna"),
    (2, "diesel"),
    (3, "LPG"),
    (4, "benzyna/lpg"),
    (5, "hybryda"),
    (6, "elektryczny")
)

CATEGORY = (
    (1, "osobowe"),
    (2, "dostawcze"),
    (3, "motocykl")
)

TYPE = (
    (1, "SUV"),
    (2, "sedan"),
    (3, "hatchback")
)

EQUIP = (
    (1, "ABS"),
    (2, "Elektryczne lusterka przednie"),
    (3, "Bluetooth"),
    (4, "ESP (stabilizacja toru jazdy)"),
    (5, "Czujniki parkowania"),
    (6, "Elektrycznie ustawiane fotele"),
    (7, "Światła LED"),
    (8, "CD "),
    (9, "Podgrzewane lusterka boczne"),
    (10, "Podgrzewane przednie siedzenia"),
    (11, "klimatyzacja"),
    (12, "Kurtyny powietrzne"),
    (13, "Isofix "),
    (14, "elektryczne lusterka tylne"),
    (15, "Centralny zamek "),
    (16, "Czujnik zmierzchu"),
    (17, "Komputer pokładowy"),
    (18, "System Start-Stop"),
    (19, "Czujnik deszczu"),
    (20, "Alarm"),
    (21, "Wielofunkcyjna kierownica"),
    (22, "Klimatyzacja automatyczna"),
    (23, "Elektryczne szyby przednie"),
    (24, "Elektryczne szyby tylne"),
    (25, "ASR (kontrola trakcji)"),
    (26, "Kamera cofania"),
    (27, "Elektrochromatyczne lusterko wsteczne"),
    (28, "Tempomat"),
    (29, "Nawigacja GPS"),
    (30, "Immobilizer"),
    (31, "Alufelgi"),


)

class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    wherefrom = models.CharField(max_length=64)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()
    
    def __str__(self):
        return self.email


class Equip(models.Model):
    equip = models.CharField(max_length=64)

    def __str__(self):
        return self.equip


class Offer(models.Model):
    car_brand = models.CharField(max_length=64, verbose_name="Marka")
    car_model = models.CharField(max_length=64, verbose_name="Model")
    category = models.IntegerField(choices=CATEGORY, verbose_name="Kategoria")
    type = models.IntegerField(choices=TYPE, verbose_name="Typ")
    year_of_production = models.SmallIntegerField(verbose_name="Rok produkcji")
    color = models.CharField(max_length=64, verbose_name="Kolor")
    car_mileage = models.IntegerField(verbose_name="Przebieg")
    description = models.TextField(verbose_name="Opis")
    car_equipment = models.ManyToManyField(Equip, verbose_name="Wyposażenie")
    fuel_type = models.IntegerField(choices=FUEL_TYPE, verbose_name="Rodzaj paliwa")
    doors_number = models.IntegerField(choices=DOORS_NUMBER, verbose_name="Liczba drzwi")
    seats_number = models.IntegerField(choices=SEATS_NUMBER, verbose_name="Liczba siedzeń")
    engine_capacity = models.IntegerField(verbose_name="Pojemność silnika")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Wystawiający")
    price = models.IntegerField(verbose_name="Cena")
    photos = models.ImageField(upload_to='media')
    photos_2 = models.ImageField(upload_to='media', null=True, blank= True)
    photos_3 = models.ImageField(upload_to='media', null=True, blank= True)
    photos_4 = models.ImageField(upload_to='media', null=True, blank= True)
    photos_5 = models.ImageField(upload_to='media', null=True, blank= True)


    def __str__(self):
        return self.car_brand + " " + self.car_model

AutoZdam/Auto_Zdam/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic.edit import CreateView, FormView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import User, Offer, Equip
from .forms import OfferForm, UserCreateForm, UserLoginForm, ContactForm
from .tokens import user_tokenizer
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.models import User as DjangoUser
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from .filters import OfferFilter
from django.conf import settings
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.core.mail import EmailMessage
from django.template.loader import get_template
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.forms import AuthenticationForm







class AddOffer(LoginRequiredMixin, View):
    # login_url = reverse_lazy('user-login')


    def get(self, request):
        form = OfferForm(request.user)
        current_user = request.user
        user_id = current_user.id
        return render(request, "Auto_Zdam/offer_form.html", {"form": form, "id": user_id})
    def post(self, request):
        f = OfferForm(request.user, request.POST, request.FILES)
        if f.is_valid():
            f.save()
        else:
            print(f.errors)
            return render(request, "Auto_Zdam/offer_form.html", {"form": f})
        return redirect(reverse('main'))

class UserCreate(View):
    def get(self, request):
        return render(request, "Auto_Zdam/register.html", { 'form': UserCreateForm() })


#url for localhost = 'http://localhost:8000' + reverse('confirm_email', kwargs={'user_id': user_id, 'token': token})
#            message = get_template('Auto_Zdam/register_email.html').render({
#                'confirm_url': url
#            })
    def post(self, request):
        form = UserCreateForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            wherefrom = form.cleaned_data['wherefrom']
            user = User.objects.create_user(email=email, password=password, first_name=first_name, last_name=last_name, wherefrom=wherefrom )
            user.save()
            user.is_active = False
            user.save()
            token = user_tokenizer.make_token(user)
            user_id = urlsafe_base64_encode(force_bytes(user.id))
            url = 'http://autozdam.pythonanywhere.com/' + reverse('confirm_email', kwargs={'user_id': user_id, 'token': token})
            message = get_template('Auto_Zdam/register_email.html').render({
                'confirm_url': url
            })
            mail = EmailMessage('Django Survey Email Confirmation', message, to=[user.email],
                                from_email='swierad@gmail.com')
            mail.content_subtype = 'html'
            mail.send()

            return render(request, "Auto_Zdam/user_login.html", {
                'form': AuthenticationForm(),
                'message': f'A confirmation email has been sent to {user.email}. Please confirm to finish registering'
            })

        return render(request, 'Auto_Zdam/register.html', {'form': form})


class ConfirmRegistrationView(View):
    def get(self, request, user_id, token):
        user_id = force_text(urlsafe_base64_decode(user_id))

        user = User.objects.get(pk=user_id)

        context = {
            'form': UserLoginForm(),
            'message': 'Registration confirmation error . Please click the reset password to generate a new confirmation email.'
        }
        if user and user_tokenizer.check_token(user, token):
            user.is_active = True
            user.save()
            context['message'] = 'Rejestracja zakończona. Zaloguj się'
            return render(request, "Auto_Zdam/user_login.html", context)

        return render(request, "Auto_Zdam/user_login.html", context)





        

class EquipCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'Auto_Zdam.add_equipe'
    login_url = reverse_lazy('user-login')
    model = Equip
    fields = '__all__'
    success_url = reverse_lazy("/add_equip")

class MainView(View):
    def get(self, request):
        offer_list = Offer.objects.all()
        offer_sample = offer_list[:10]
        no_of_offers = offer_list.count()
        no_of_users = User.objects.count()
        offerFilter = OfferFilter(request.GET, queryset=offer_list)
        offer_list = offerFilter.qs
        form = OfferForm(request.user)
        current_user = request.user
        user_id = current_user.id
        contact_form = ContactForm()
        


        ctx = {
            'no_of_offers': no_of_offers,
            'no_of_users': no_of_users,
            'offerFilter': offerFilter,
            'offer_sample': offer_sample,
            "form": form,
            "id": user_id,
            "contact_form": contact_form
        }
        return render(request, "Auto_Zdam/index.html", ctx)
    
    def post(self, request):
        form = OfferForm(request.user)        
        current_user = request.user
        user_id = current_user.id
        price = request.POST.get("price")
        car_brand = request.POST.get("car_brand")
        car_model = request.POST.get("car_model")
        year_of_production = request.POST.get("year_of_production")
        engine_capacity = request.POST.get("engine_capacity")
        ctx = {'car_brand': car_brand, 'car_model': car_model, 'year_of_production': year_of_production, 'engine_capacity': engine_capacity, 'price': price, "form": form, "id": user_id}

        if user_id == None:    
            return render(request, "Auto_Zdam/user_login.html")
        else:
            return render(request, "Auto_Zdam/offer_form.html", ctx)


class UserLoginView(View):
    def get(self, request):
        form = UserLoginForm()
        return render(request, "Auto_Zdam/user_login.html", {'form': form})

    def post(self, request):
        form = UserLoginForm(request.POST)
        if form.is_valid():  # uruchomienie walidacji
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(reverse('main'))
                else:
                    form.add_error(None, "Konto nie jest aktywne")
            else:
                # user is None
                form.add_error(None, "Nieprawidłowy login lub hasło")
        return render(request, "Auto_Zdam/user_login.html", {'form': form})

class UserLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect(reverse('main'))



class OfferDetails(View):
#    permission_required = 'Auto_Zdam.view_offer'
#   PermissionRequiredMixin,
    login_url = reverse_lazy('user-login')
    def get(self, request, id):
        r = Offer.objects.get(id=id)
        ctx = {
            "offer": r,
        }
        return render(request, "Auto_Zdam/offer-details.html", ctx)
    #def post(self, request, id ):
    #    msg = request.POST.get("msg")
    #    send_mail('Masz nową wiadomość z poratlu AutoZdam', msg, 'swierad-88@o2.pl', ['swierad@gmail.com'], fail_silently = False)
   #     r = Offer.objects.get(id=id)
    #    ctx = {
    #        "offer": r,
   #     }
  #      return render(request, "Auto_Zdam/offer-details.html", ctx)


class OfferUpdate(UpdateView):
  model = Offer
  fields = ["car_brand", "car_model", "category", "type", "year_of_production", "color", "car_mileage",
    "description", "car_equipment", "fuel_type", "doors_number", "seats_number", "engine_capacity", "user", "price",
    "photos", "photos_2", "photos_3", "photos_4", "photos_5"]
  template_name_suffix = '_update_form'
  success_url = '/'

class OfferDelete(DeleteView):
    model = Offer
    success_url = '/'

class ContactFormView(View):
    def get(self, request, id):
        form = ContactForm()
        return render(request, "Auto_Zdam/offer-msg.html", {'form': form})
    def post(self, request, id):
        form = ContactForm(request.POST)
        r = Offer.objects.get(id=id)
        if form.is_valid():
            form = request.POST.get('description')
            form_price = request.POST.get('price')
            loged_user = request.user.email
            msg = f"Wiadomość od {loged_user} w sprawie ogłoszenia {r.car_brand} {r.car_model}: " \
                  f"{form}. Kwota proponowana przez komisanta {form_price}   "
            send_mail(f'Auto_Zdam - masz nową wiadomość od {loged_user}', msg, 'swierad-88@o2.pl', ['swierad@gmail.com'], fail_silently = False)
            r = Offer.objects.get(id=id)
            ctx = {
                "offer": r,
            }
            return render(request, "Auto_Zdam/offer-details.html", ctx)


class MyView(View):
    def get(selfself, request):
        user = User.objects.get(email = request.user.email)
        offers = Offer.objects.filter(user = user)
        ctx = {
            "user":  request.user,
            "offers": offers
        }
        return render(request, "Auto_Zdam/MyView.html", ctx)
    

class OfferListView(View):
    def get(self, request):
        offer_list = Offer.objects.order_by('id')
        offerFilter = OfferFilter(request.GET, queryset=offer_list)
        offer_list = offerFilter.qs
        paginator = Paginator(offer_list, 5)

AutoZdam/Auto_Zdam/templates/Auto_Zdam/equip_form.html
<form action="" method="post">
  {% csrf_token %}
    dodawajka wyposażenia
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>

AutoZdam/Auto_Zdam/templates/Auto_Zdam/offer-details.html
<form action="" method="post" class='mx-6'>

{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}

<br>
<br>

  <div class="columns">
    <div class="column">
      <p>
        <h1 class="margin"> {{offer.car_brand}} {{ offer.car_model }} </h1>
        <h3>  CENA: {{ offer.price }} PLN</h3>
      {% if  offer.user|stringformat:'s'  == user.get_username|stringformat:'s'%}
        <a href="{% url 'offer-update' offer.id %}"> edytuj ofertę | </a> <a href="{% url 'offer-delete' offer.id %}"> usuń ofertę</a>
      {% else %}
        <a href="{% url 'offer-msg' offer.id %}">skontaktuj się z Wystawiającym:</a>
      {% endif %}
      </p>
    </div>
  </div>
<br>

<div class="columns">
  <div class="column">
    <div class="bxslider ">
      <div><img src="{{offer.photos.url}}"> </div>
          {% if offer.photos_2.url != None %}
       <div><img src="{{offer.photos_2.url}}"> </div>
          {% endif %}
          {% if offer.photos_3.url != None %}
       <div><img src="{{offer.photos_3.url}}"> </div>
          {% endif %}
          {% if offer.photos_4.url != None %}
       <div><img src="{{offer.photos_4.url}}"> </div>
          {% endif %}
          {% if offer.photos_5.url != None %}
       <div><img src="{{offer.photos_5.url}}"> </div>
          {% endif %}
    </div>
  </div>
  <div class="column">
    <p class='has-text-centered has-text-justified'>{{offer.description}}</p>
  </div>
</div>

<div class="columns">
  <div class="column">
    <p class="has-text-centered">
      <strong>Informacje ogólne:</strong>
    </p>
    <br>
    <nav class="level">
    <div class="level-item has-text-centered">
      <div>
          <div id="offer_one">
                  marka pojazdu: <strong>{{offer.car_brand}}</strong> <br>
                  model pojazdu: <strong>{{offer.car_model}}</strong> <br>
                  kategoria: <strong>{{offer.get_category_display}}</strong> <br>
                  typ: <strong>{{offer.get_type_display}}</strong> <br>
                  kolor: <strong>{{offer.color}}</strong> <br>
                  rok produkcji: <strong>{{offer.year_of_production}}</strong>
          </div>
      </div>
    </div>
    <div class="level-item has-text-centered">
      
          <div id="offer_two">
                  rodzaj paliwa: <strong>{{offer.get_fuel_type_display}}</strong> <br>
                  liczba drzwi: <strong>{{offer.doors_number}}</strong> <br>
                  liczba miejsc: <strong>{{offer.seats_number}}</strong> <br>
                  przebieg: <strong>{{offer.car_mileage}}</strong> <br>
                  pojemność skokowa: <strong>{{offer.engine_capacity}}</strong> <br>
          </div>
    </div>
    </nav>
    
  </div>
  <div class="column ">
    
    <p>
      <strong class='has-text-centered'>Wyposażenie:</strong>
    </p>
    <br>
    <ul>
    {% for i in offer.car_equipment.all %}
        <li>
          <span><i class="fas fa-circle"></i></span> {{ i.equip }};
        </li>
    {% endfor %}
    </ul>
    <br>
  </div>
</div>

{% endblock content %}

</form>

AutoZdam/Auto_Zdam/templates/Auto_Zdam/offer-msg.html
<html>
  <form action="" method="post">
    {% extends "base.html" %} {% block content %} {% load widget_tweaks %}
    {%csrf_token %}

    <br />
    <div class="columns">
      <div class="column is-desktop"></div>
      <div class="column">
        <h1 class="title is-3 has-text-centered">
          Skontaktuj się z wystawiającym
        </h1>

        <div class="field">
          <label for="{{ form.description.id_for_label }}" class="label has-text-centered">treść wiadomości</label>
          <div class="control">
            <textarea
              class="textarea"
              placeholder="treść wiadomości"
              name="description"
              cols="40"
              rows="10"
              required
              id="id_description">
            </textarea>
          </div>
        </div>

        <div class="field">
          <label for="{{ form.price.id_for_label }}" class="label has-text-centered">proponowana kwota</label>
          <div class="control">
            <input
              class="input is-info"
              type="number"
              placeholder="proponowana kwota"
              name="price"
              required
              id="id_price"
            />
          </div>
        </div>

        <br>
        <div class="field is-grouped">
          <div class="control">
            <button class="button is-link">wyślij wiadomość</button>
          </div>
        </div>
      </div>
      <div class="column"></div>
    </div>

    {% endblock content %}
  </form>
</html>

AutoZdam/Auto_Zdam/templates/Auto_Zdam/offer_list.html
<form action="" method="get">

{% extends "base.html" %}

{% block content %}
{% csrf_token %}
<br>
<div class='mx-6'>
    <form method = "get">
        {{ offerFilter.form}}
        <input type="submit" value="szukaj">
    </form>
    <br>
    <br>
    {% for i in r %}



    <div class="columns is-mobile">
    <div class="column is-half-mobile is-two-thirds-tablet is-half-desktop is-one-third-widescreen is-one-quarter-fullhd">
        <a href={% url 'offer-details' i.id %}><img src="{{i.photos.url}}" width="100%" alt="mapa"> </a>

    </div>
    <div class="column">
        <a href={% url 'offer-details' i.id %} class='is-size-7-mobile'> &nbsp&nbsp {{i.car_brand}} {{ i.car_model }} <br> &nbsp&nbsp Cena: {{i.price}} PLN <br> &nbsp&nbsp rocznik: {{ i.year_of_production }} <br> &nbsp&nbsp lokalizacja: {{ i.user.wherefrom}} <br> &nbsp&nbsp przebieg: {{ i.car_mileage }}&nbspkm <br> &nbsp&nbsp pojemność:{{ i.engine_capacity }}&nbspcm3 <br>&nbsp&nbsp rodzaj paliwa: {{ i.get_fuel_type_display }} </a>
    </div>
    <div class="column visibility-desktop is-hidden-touch">
        <a> opis: <br> {{ i.description }}</a>
    </div>

    </div>

    </section>
    {% endfor %}

    <nav class="pagination is-rounded" role="navigation" aria-label="pagination">
        {% if r.has_previous %}
            <a class="pagination-previous" href="?page={{ r.previous_page_number }}">poprzednia strona</a>
        {% endif %}
        {% if r.has_next %}
        <a class="pagination-next" href="?page={{ r.next_page_number }}">następna strona</a>
        {% endif %}
        <ul class="pagination-list">
          {% if r.previous_page_number == 1 or r.number == 1 %}

          {% else %}
          <li><a class="pagination-previous" href="?page=1">1</a></li>
          <li><span class="pagination-ellipsis">&hellip;</span></li>
          {% endif %}
          {% if r.has_previous %}
          <li><a class="pagination-link" href="?page={{ r.previous_page_number }} aria-label="{{ r.previous_page_number }}">{{ r.previous_page_number }}</a></li>
          {% endif %}
          <li><a class="pagination-link is-current" aria-label="{{ r.number }}" aria-current="page">{{ r.number }}</a></li>
          {% if r.has_next %}
          <li><a class="pagination-link" href="?page={{ r.next_page_number }}" aria-label="{{ r.next_page_number }}">{{ r.next_page_number }}</a></li>
          {% endif %}
          {% if r.next_page_number == r.paginator.num_pages or r.number == r.paginator.num_pages %}

          {% else %}
          <li><span class="pagination-ellipsis">&hellip;</span></li>
          <li><a class="pagination-previous" href="?page={{page_obj.paginator.num_pages}}">{{r.paginator.num_pages}}</a></li>
          {% endif %}

        </ul>
      </nav>

{% endblock content %}

AutoZdam/Auto_Zdam/templates/Auto_Zdam/register.html
<form action="" method="post" enctype="multipart/form-data">
   {% extends "base.html" %}
{% block content %}

  {% load widget_tweaks %}

  {% csrf_token %}
<br class='is-desktop'>
<br class='is-desktop'>
<br class='is-desktop'>

<div class="columns is-mobile">
  <div class="column is-desktop"></div>
  <div class="column is-three-quarters">
    <h1 class="title is-3 has-text-centered">Zarejestruj się</h1>
<br>
<br>
<br>

 

<div class="box register_box">

  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <label for="{{ form.email.id_for_label }}" class="label">Email:</label>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control is-expanded has-icons-left">
          <input class="input" type="email" placeholder="Email" name="email" maxlength="254" required id="id_email">
          <span class="icon is-small is-left">
            <i class="fas fa-envelope"></i>
          </span>
        </p>
      </div>

    </div>
  </div>


  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <label for="{{ form.password.id_for_label }}" class="label"> Hasło: </label>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control is-expanded has-icons-left">
          <input class="input" type="password" placeholder="***" name="password" maxlength="128" required id="id_password">
          <span class="icon is-small is-left">
            <i class="fas fa-key"></i>
          </span>
        </p>
      </div>
      <div class="field-label is-normal">
      <label for="{{ form.password2.id_for_label }}" class="label">Potwierdź hasło:</label>
    </div>
      <div class="field">
        <p class="control is-expanded has-icons-left has-icons-right">
          <input class="input" type="password" placeholder="***" name="password2" required id="id_password2">
          <span class="icon is-small is-left">
            <i class="fas fa-key"></i>
          </span>
        </p>
      </div>
    </div>
  </div>


  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <label for="{{ form.name.id_for_label }}" class="label">Imię:</label>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control is-expanded has-icons-left">
          <input class="input" type="text" placeholder="Jan" name="first_name" maxlength="30" id="id_first_name">
          <span class="icon is-small is-left">
            <i class="fas fa-user-alt"></i>
          </span>
        </p>
      </div>
      <div class="field-label is-normal">
      <label for="{{ form.surname.id_for_label }}" class="label">Naziwsko:</label>
    </div>
      <div class="field">
        <p class="control is-expanded has-icons-left has-icons-right">
          <input class="input" type="text" placeholder="Nowak" name="last_name" maxlength="150" id="id_last_name">
          <span class="icon is-small is-left">
            <i class="fas fa-user-alt"></i>
          </span>

        </p>
      </div>
    </div>
  </div>


  <div class="field is-horizontal">
    <div class="field-label is-normal">
      <label for="{{ form.wherefrom.id_for_label }}" class="label">Lokalizacja:</label>
    </div>
    <div class="field-body">
      <div class="field">
        <p class="control is-expanded has-icons-left">
          <input class="input" type="text" placeholder="Warszawa" name="wherefrom" maxlength="64" required id="id_wherefrom">
          <span class="icon is-small is-left">
            <i class="fas fa-map-marker-alt"></i>
          </span>
        </p>
        <br>
        <div class="field is-grouped">
          <div class="control">
            <button class="button is-link">Zarejestruj</button>
          </div>
        </div>
      </div>

    </div>
  </div>

</div>
  </div>
  <div class="column"></div>
  
</div>

    

</form>
{% endblock content %}

AutoZdam/Auto_Zdam/templates/Auto_Zdam/thx.html
<form action="" method="post">

  dzięki!
  <input type="submit" value="Save">
</form>